project_id = "dmklwxdiowibtdkehekq"

[functions.handle-signup]
enabled = true
verify_jwt = true
import_map = "./functions/handle-signup/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle-signup/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle-signup/*.html" ]

[functions.kickstart-cycle]
enabled = true
verify_jwt = true
import_map = "./functions/kickstart-cycle/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/kickstart-cycle/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/kickstart-cycle/*.html" ]

[functions.calculate-usd-to-brl]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-usd-to-brl/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-usd-to-brl/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-usd-to-brl/*.html" ]

[functions.sync-cycle]
enabled = true
verify_jwt = true
import_map = "./functions/sync-cycle/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-cycle/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-cycle/*.html" ]
